; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.26"

; Modules
projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.2"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[composer_manager][subdir] = "contrib"
projects[composer_manager][version] = "1.0-rc1"

projects[devel][subdir] = "contrib"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.3"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.1"

projects[features][subdir] = "contrib"
projects[features][version] = "2.0"

projects[github_api][subdir] = "contrib"
projects[github_api][version] = "1.0-alpha2"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.3"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "2.0-alpha2"

projects[og][subdir] = "contrib"
projects[og][version] = "2.4"

projects[services][subdir] = "contrib"
projects[services][version] = "3.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

; Themes
projects[bootstrap][version] = "3.0"

; Modules
projects[behat_editor][download][type] = "git"
projects[behat_editor][download][url] = "https://github.com/alnutile/behat_editor.git"
projects[behat_editor][type] = "module"

projects[behat_editor_saucelabs][download][type] = "git"
projects[behat_editor_saucelabs][download][url] = "https://github.com/alnutile/behat_editor_saucelabs.git"
projects[behat_editor_saucelabs][type] = "module"

projects[github_behat_editor][download][type] = "git"
projects[github_behat_editor][download][url] = "https://github.com/alnutile/github_behat_editor.git"
projects[github_behat_editor][type] = "module"

projects[simple_noty][download][type] = "git"
projects[simple_noty][download][url] = "https://github.com/alnutile/simple_noty.git"
projects[simple_noty][type] = "module"
